### ISSUE TITLE
coordinate system unification

### ISSUE THREAD

**Issue by rannan09** [CSID-DGU/2019-1-OSSP2-Openthedoor-7#3]
OpenCV와 OpenGL의 좌표계 불일치 문제

**Comment by KIMYYEJI** [comment]
OpenCV의 좌표계는  왼쪽상단이 원점이었으나 현재 OpenGL과 연동을 한 상태는 화면의 중점이 원점임을 여러번의 실행끝에 알게되었다. 
웹캠의 화면 크기(640*480)를 알고 좌표계를  gluOrtho2D(-width, width, -height, height); 함수를 사용하여 중점이 (0,0) 원점이고 x축의 최댓값을 width(640), 최솟값을 -width(-640) / y축의 최댓값을 height(480), 최솟값을 -height(-480)인 환경으로 설정하였다. 
=> 이 방법으로 두 좌표계 일치시킴

**Comment by rannan09** [comment]
감사합니다 :)
