### ISSUE TITLE
Print life symbol to display

### ISSUE THREAD

**Issue by rannan09** [CSID-DGU/2019-1-OSSP2-Openthedoor-7#5]
문제 ) 남은 생명의 수를 화면에 출력해야하는데 OpenCV의 putText()함수는 아스키코드만을 반영하여 하트 이모티콘 작성시 ???로 나오는 문제

해결방안)
1) 이미지를 만경들어 관심영역을 지정하여 life 수에 따라 출력되는 이미지 변경
2) OpenGL로 하트 도형을 그려 life 수에 따라 출력되는 도형의 갯수 변경
3) 정수형의 남은 life 수 출력

**Comment by KIMYYEJI** [comment]
제가 OpenGL로 하트를 그려서 출력시킬 수 있을 것 같습니다.
그래서 그 하트를 먹으면 생명이 추가되는 방식으로 하고 그 하트 도형을 사용하여 남은 life 수를 보여주는 게 좋을 거 같아서 2번이 가장 적합한 해결 방안 같습니다.

**Comment by rannan09** [comment]
해결했습니다~
