### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by hyex** [CSID-DGU/2019-1-OSSP2-Openthedoor-7#7]
test the executed file of socket_programming.c .
Then an error will occur at app.js (96) 
I think we check
1. RDS user_idx datatype is int ?
2. what is type of myId and myPwd in socket_programming.c ? ( becuause pwd error is occured ,, )
and more.

**Comment by shinsohui** [comment]
postman을 통해 넣어진 id, pw는 c++ 코드를 통해 넘어간 값이 아니기때문에 해싱 값이 다른게 나온 것으로 판단 됨 
로그인, 회원 가입 기능을 반드시 c++ 코드를 돌려서 확인해볼 것
